version: '3'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    networks:
      - kafka_net
    ports:
      - "2181:2181"

  kafka:
    image: wurstmeister/kafka
    networks:
      - kafka_net
    ports:
      - "9092:9092"
    environment:
      KAFKA_LISTENERS: EXTERNAL_SAME_HOST://:29092,INTERNAL://:9092
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka:9092,EXTERNAL_SAME_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL_SAME_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: "logs:1:1"
    depends_on:
      - zookeeper

  app:
    networks:
      - kafka_net
    build:
      context: ./app
      dockerfile: Dockerfile
    # depends_on:
    #   - kafka
    environment:
      FASTIFY_PORT: $APP_PORT
      FASIFTY_ADDRESS: $APP_HOST
      KAFKA_BROKER: kafka:9092
      RPC_MAINNET_WS: $RPC_MAINNET_WS
      RPC_MAINNET_HTTP: $RPC_MAINNET_HTTP
    volumes:
      - ./app:/app

networks:
  kafka_net: